.read migrations/0001_init.sql
.read migrations/0002_game_code_plain.sql
.read migrations/0003_invite_code_nullable.sql
.read migrations/0004_user_ban_fields.sql
.read migrations/0005_name_change_cooldown.sql
.read migrations/0006_dummy_login_code.sql
.read migrations/0007_dummy_name.sql
.read migrations/0008_email_verification.sql
.read migrations/0009_dummy_name_change_cooldown.sql
.read migrations/0010_user_admin_flag.sql
.read migrations/0011_billing_subscriptions.sql
.read migrations/0012_billing_webhook_events.sql
.read migrations/0013_patreon_connections.sql
.read migrations/0014_billing_entitlements.sql
.read migrations/0015_billing_tier_rules.sql
.read migrations/0016_patreon_oauth_states.sql
.read migrations/0017_user_invite_quota_base.sql
.read migrations/0018_user_auto_login_settings.sql
.read migrations/0019_admin_map_uploads.sql
.read migrations/0020_user_display_name.sql
