name = "ddnet-website"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ddnet_req_login"
database_id = "413951e9-8380-4cd0-8a61-3437ef97a093"
preview_database_id = "413951e9-8380-4cd0-8a61-3437ef97a093"

[[r2_buckets]]
binding = "MAPS_BUCKET"
bucket_name = "ddnet-map-uploads"
